# Generated by Django 4.1.6 on 2023-02-08 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeHouse',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='house.basemodel')),
                ('name', models.CharField(max_length=255)),
            ],
            bases=('house.basemodel',),
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='house.basemodel')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.typehouse')),
            ],
            bases=('house.basemodel',),
        ),
    ]
