# Generated by Django 4.1.6 on 2023-02-08 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typehouse',
            name='basemodel_ptr',
        ),
        migrations.DeleteModel(
            name='House',
        ),
        migrations.DeleteModel(
            name='TypeHouse',
        ),
    ]
