# Generated by Django 4.1.6 on 2023-02-08 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_remove_typehouse_basemodel_ptr_delete_house_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('дом', 'ДОМ'), ('квартира', 'КВАРТИРА'), ('дача', 'ДАЧА')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Dacha',
            fields=[
                ('house_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='house.house')),
                ('title', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
            ],
            bases=('house.house',),
        ),
        migrations.CreateModel(
            name='Kvarira',
            fields=[
                ('house_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='house.house')),
                ('title', models.CharField(max_length=255)),
            ],
            bases=('house.house',),
        ),
    ]
