# Generated by Django 4.1.6 on 2023-02-08 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_house_dacha_kvarira'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kvarira',
            new_name='Kvartira',
        ),
    ]
